# Tomcat
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /iot-modbus-test

iot:
  netty: # netty通讯
    open: true
    port: 4000
    thread: 10
